import { Suspense } from 'react'
import './global.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  viewport: {
    width: 'device-width',
    initialScale: 1,
  },
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
    other: [
      {
        rel: 'icon',
        url: '/favicon-16x16.png',
        sizes: '16x16',
      },
      {
        rel: 'icon',
        url: '/favicon-32x32.png',
        sizes: '32x32',
      },
    ],
} }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      
        <header>
          <h1 className="bg-red text-3xl">Next.js Application</h1>
        </header>
        {children}
        <Suspense fallback={<p>Loading...</p>}>
          <main className="container mx-auto p-4">
          <img src="https://wallpaperaccess.com/full/8359972.jpg"></img>
          </main>
         </Suspense>
        <footer>
          <p>© 2023 Next.js App</p>
        </footer>
        </body>
    </html>
  )
}
